"""M0.3 - which strategy produces publishable Uzbek?

Three strategies, two models, ten articles. Batched by model: all work for one model
completes before the other loads, because a model swap costs ~11s (see OLLAMA_BENCHMARK).

Usage:  python probe_language.py
"""

import json
import sys
import time
from pathlib import Path

import httpx

sys.path.insert(0, str(Path(__file__).parent))
from probe_ollama import OUT, base_url  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

FAST = "gemma4:latest"
DEEP = "gemma4:31b"

# --- Strategy A: ask in Uzbek, answer in Uzbek --------------------------------
A_PROMPT = """Siz AI-muhandislik yangiliklari dayjesti muharrirsiz. Auditoriya —
rahbarlar va texnik mutaxassislar.

Quyidagi maqolani o'qing va o'zbek tilida 3-4 gapdan iborat xulosa yozing.

Xulosada bo'lishi kerak:
- nima yaratildi yoki e'lon qilindi
- nega bu muhim
- kim uchun amaliy foydasi bor

Faqat xulosani yozing, sarlavha va izohsiz.

MAQOLA
Sarlavha: {title}
---
{text}
"""

# --- Strategy B: English summary, then a separate translation call ------------
B_SUMMARY_PROMPT = """You are an editor for an AI-engineering news digest.
Read the article and write a 3-4 sentence summary covering: what was built or announced,
why it matters, and who benefits practically. Output the summary only.

ARTICLE
Title: {title}
---
{text}
"""

B_TRANSLATE_PROMPT = """Translate the following text into Uzbek (latin script).

Rules:
- Keep technical terms in English: model, API, agent, framework, open-source,
  benchmark, context, token, repository.
- Natural Uzbek, not word-by-word translation.
- Same number of sentences.
- Output the translation only.

TEXT
{text}
"""

# --- Strategy C: reason in English, emit Uzbek in a structured field ----------
C_SCHEMA = {
    "type": "object",
    "properties": {
        "reasoning_en": {"type": "string"},
        "summary_uz": {"type": "string"},
    },
    "required": ["reasoning_en", "summary_uz"],
}

C_PROMPT = """You are an editor for an AI-engineering news digest read in Uzbekistan.

Think in English, then write the reader-facing summary in Uzbek.

- reasoning_en: your analysis in English. What was built, why it matters, who benefits.
- summary_uz: 3-4 sentences in Uzbek (latin script) for the digest. Keep technical terms
  in English (model, API, agent, framework, open-source, benchmark, context, token).
  This field is published as-is, so it must read naturally.

ARTICLE
Title: {title}
---
{text}
"""


def call(client, model, prompt, schema=None):
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
        "options": {"temperature": 0},
    }
    if schema:
        payload["format"] = schema
    t0 = time.perf_counter()
    try:
        r = client.post(f"{base_url()}/api/chat", json=payload)
        dt = time.perf_counter() - t0
        r.raise_for_status()
        return r.json()["message"]["content"].strip(), round(dt, 2), None
    except Exception as e:  # noqa: BLE001
        return None, round(time.perf_counter() - t0, 2), f"{type(e).__name__}: {e}"


def run_model(model, arts, timeout):
    """All three strategies for one model, so the model loads exactly once."""
    out = []
    print(f"\n=== {model} ===")
    with httpx.Client(timeout=timeout) as c:
        for i, a in enumerate(arts, 1):
            text = a["text"][:8000]
            row = {"title": a["title"], "url": a["url"]}

            txt, dt, err = call(c, model, A_PROMPT.format(title=a["title"], text=text))
            row["A"] = {"text": txt, "seconds": dt, "error": err, "calls": 1}

            en, dt1, e1 = call(c, model, B_SUMMARY_PROMPT.format(title=a["title"], text=text))
            if en:
                uz, dt2, e2 = call(c, model, B_TRANSLATE_PROMPT.format(text=en))
            else:
                uz, dt2, e2 = None, 0.0, e1
            row["B"] = {"text": uz, "english": en, "seconds": round(dt1 + dt2, 2),
                        "error": e1 or e2, "calls": 2}

            raw, dt, err = call(c, model, C_PROMPT.format(title=a["title"], text=text), C_SCHEMA)
            try:
                parsed = json.loads(raw) if raw else {}
                row["C"] = {"text": parsed.get("summary_uz"),
                            "reasoning": parsed.get("reasoning_en"),
                            "seconds": dt, "error": err, "calls": 1}
            except json.JSONDecodeError as e:
                row["C"] = {"text": None, "seconds": dt, "error": f"bad json: {e}", "calls": 1}

            out.append(row)
            print(f"  {i:>2}/{len(arts)}  A={row['A']['seconds']:>6.2f}s  "
                  f"B={row['B']['seconds']:>6.2f}s  C={row['C']['seconds']:>6.2f}s  "
                  f"{a['title'][:44]}")
    return out


def write_report(results, arts):
    L = []
    L.append("# M0.3 — Uzbek Output Quality\n")
    L.append("Date: 2026-08-14  \nGenerated by `spikes/probe_language.py`\n")
    L.append("## How to score\n")
    L.append("Read each Uzbek summary and fill the table in section 2. Scale:\n")
    L.append("| Score | Meaning |\n|---|---|")
    L.append("| 5 | Publish as-is |")
    L.append("| 4 | One small word change |")
    L.append("| 3 | Understandable, needs editing |")
    L.append("| 2 | Awkward, would embarrass us |")
    L.append("| 1 | Wrong or unreadable |\n")
    L.append("Strategies: **A** direct Uzbek · **B** English summary then translate "
             "(2 calls) · **C** reason in English, emit `summary_uz` (1 call)\n")

    L.append("## 1. Cost per strategy\n")
    L.append("| Model | Strategy | Calls/article | Mean seconds |\n|---|---|---|---|")
    for model, rows in results.items():
        for s in ("A", "B", "C"):
            ok = [r[s]["seconds"] for r in rows if r[s].get("text")]
            mean = f"{sum(ok) / len(ok):.2f}" if ok else "n/a"
            L.append(f"| `{model}` | {s} | {rows[0][s]['calls']} | {mean} |")

    L.append("\n## 2. Scoring table — fill this in\n")
    L.append("| # | Article | 8B-A | 8B-B | 8B-C | 31B-A | 31B-B | 31B-C |\n"
             "|---|---|---|---|---|---|---|---|")
    for i, a in enumerate(arts, 1):
        L.append(f"| {i} | {a['title'][:44]} |  |  |  |  |  |  |")
    L.append("\n**Chosen strategy:** _______   **Reason:** _______\n")

    L.append("## 3. Generated text\n")
    for i, a in enumerate(arts, 1):
        L.append(f"### {i}. {a['title']}\n")
        L.append(f"<{a['url']}>\n")
        for model, rows in results.items():
            r = rows[i - 1]
            label = "8B" if model == FAST else "31B"
            for s in ("A", "B", "C"):
                cell = r[s]
                L.append(f"**{label} — strategy {s}** ({cell['seconds']}s)\n")
                if cell.get("error"):
                    L.append(f"> ERROR: {cell['error']}\n")
                else:
                    L.append(f"> {cell['text']}\n")
        L.append("---\n")

    path = Path(__file__).parent.parent / "docs" / "spike" / "LANGUAGE_QUALITY.md"
    path.write_text("\n".join(L), encoding="utf-8")
    print(f"\n-> {path}")


if __name__ == "__main__":
    arts = json.loads((OUT / "sample_articles.json").read_text(encoding="utf-8"))
    results = {}
    results[FAST] = run_model(FAST, arts, 120)
    results[DEEP] = run_model(DEEP, arts, 600)
    (OUT / "language_raw.json").write_text(
        json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
    write_report(results, arts)
