# Generated by Django 6.0.8 on 2026-08-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(max_length=1000, unique=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('extracted_text', models.TextField()),
                ('status', models.CharField(choices=[('fetched', 'Fetched'), ('triaged', 'Triaged'), ('classified', 'Classified'), ('skipped', 'Skipped')], db_index=True, default='fetched', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('composed', 'Composed'), ('published', 'Published'), ('failed', 'Failed')], default='composed', max_length=20)),
                ('composed_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-digest_date'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('connector', models.CharField(choices=[('rss', 'Rss'), ('github', 'Github'), ('hn', 'Hn'), ('html', 'Html')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('stream', models.CharField(blank=True, choices=[('frontier_models', 'Frontier Models'), ('ai_agents', 'Ai Agents'), ('new_approaches', 'New Approaches'), ('speech_voice', 'Speech Voice'), ('robotics', 'Robotics'), ('fintech', 'Fintech'), ('govtech', 'Govtech'), ('production_engineering', 'Production Engineering'), ('startups', 'Startups'), ('technical_talks', 'Technical Talks'), ('safety_security', 'Safety Security'), ('irrelevant', 'Irrelevant')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('is_degraded', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('last_alerted_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_tag', models.CharField(max_length=60)),
                ('model_digest', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='digest.article')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('group_message_id', models.BigIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='digest.article')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digest.digest')),
            ],
            options={
                'ordering': ['digest', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('reaction', models.CharField(choices=[('useful', 'Useful'), ('not_useful', 'Not Useful'), ('want_to_build', 'Want To Build')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='digest.digestitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='digest.source'),
        ),
        migrations.AddConstraint(
            model_name='digestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'position'), name='unique_digest_position'),
        ),
        migrations.AddConstraint(
            model_name='digestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'article'), name='unique_digest_article'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('digest_item', 'user_id'), name='one_reaction_per_user_per_item'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'status'], name='digest_arti_source__5122a1_idx'),
        ),
    ]
