# Generated by Django 6.0.8 on 2026-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('rss', 'Rss'), ('github', 'Github'), ('hn', 'Hn'), ('hf', 'Hf'), ('html', 'Html')], max_length=20),
        ),
    ]
