# Generated by Django 6.0.8 on 2026-08-17 07:24

from django.db import migrations, models


def backfill_analysis_stage(apps, schema_editor):
    Analysis = apps.get_model('digest', 'Analysis')
    Analysis.objects.filter(stage='').update(stage='classification')


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_alter_source_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('classification', 'Classification'), ('editorial', 'Editorial')], db_index=True, default='classification', max_length=20),
        ),
        migrations.AddField(
            model_name='digestitem',
            name='secondary_articles',
            field=models.ManyToManyField(blank=True, related_name='secondary_in_digest_items', to='digest.article'),
        ),
        migrations.RunPython(backfill_analysis_stage, reverse_code=migrations.RunPython.noop),
    ]
