# Generated by Django 6.0.8 on 2026-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0003_analysis_stage_digestitem_secondary_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='stage',
            field=models.CharField(choices=[('triage', 'Triage'), ('classification', 'Classification'), ('editorial_en', 'Editorial En'), ('editorial_uz', 'Editorial Uz'), ('editorial', 'Editorial')], db_index=True, default='classification', max_length=20),
        ),
    ]
