# Generated by Django 6.0.8 on 2026-08-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_alter_analysis_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artifact_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='artifact_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
