# Generated by Django 6.0.8 on 2026-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0005_article_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestitem',
            name='sent_as_photo',
            field=models.BooleanField(default=False, help_text='Whether this item was published to the channel as a photo with caption'),
        ),
    ]
