# Generated by Django 6.0.8 on 2026-08-19 14:08

from django.db import migrations, models


def backfill_delivery_states(apps, schema_editor):
    DigestItem = apps.get_model("digest", "DigestItem")
    DigestItem.objects.filter(channel_message_id__isnull=False).update(channel_delivery_state="sent")


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0006_digestitem_sent_as_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestitem',
            name='channel_delivery_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digestitem',
            name='channel_delivery_error',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='digestitem',
            name='channel_delivery_state',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('sending', 'Sending'),
                    ('sent', 'Sent'),
                    ('unknown', 'Unknown'),
                    ('failed', 'Failed'),
                ],
                db_index=True,
                default='pending',
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_delivery_states, migrations.RunPython.noop),
    ]
