# Generated by Django 6.0.8 on 2026-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0007_digestitem_delivery_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digest',
            options={'ordering': ['-digest_date', '-edition']},
        ),
        migrations.AddField(
            model_name='digest',
            name='edition',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], db_index=True, default='evening', max_length=16),
        ),
        migrations.AlterField(
            model_name='digest',
            name='digest_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='digest',
            constraint=models.UniqueConstraint(fields=('digest_date', 'edition'), name='unique_digest_date_edition'),
        ),
    ]
