# Generated by Django 6.0.8 on 2026-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0008_alter_digest_options_digest_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='roundup_message_id',
            field=models.IntegerField(blank=True, help_text='Telegram message ID of the closing summary post in the channel.', null=True),
        ),
    ]
