# Generated by Django 6.0.8 on 2026-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0009_digest_roundup_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
